name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > id_ed25519
          chmod 600 id_ed25519

      - name: Clean frontend folder on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            mkdir -p ~/frontend
            cd ~/frontend
            rm -rf *
          EOF

      - name: Copy frontend to VPS
        run: |
          rsync -avz -e "ssh -i id_ed25519 -o StrictHostKeyChecking=no" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/frontend/

      - name: Clean up SSH key
        run: rm -f id_ed25519
